[project]
name = "piperbox"
version = "0.1.0"
description = "CLI to generate bulk text to wav files"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
